// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  apiUrl: 'https://something.com',
  pageTitle: 'The Best Blog in the World'
};
