// This file can be replaced during build by using the `fileReplacements` array.
// `ng build ---prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  apiUrl: 'http://localhost:3000',
  pageTitle: 'The Best Blog in the World!',
  authUrl: 'http://localhost:3001',
  firebase: {
    apiKey: "AIzaSyCPopbeoAHX88NJ6r36LHkHZqVbEgZmk1E",
    authDomain: "sandbox-project-278614.firebaseapp.com",
    databaseURL: "https://sandbox-project-278614.firebaseio.com",
    projectId: "sandbox-project-278614",
    storageBucket: "sandbox-project-278614.appspot.com",
    messagingSenderId: "709636273327",
    appId: "1:709636273327:web:3ed54083261e50f315105a",
    measurementId: "G-3SHKWWD8V6"
  }
};

/*
 * In development mode, to ignore zone related error stack frames such as
 * `zone.run`, `zoneDelegate.invokeTask` for easier debugging, you can
 * import the following file, but please comment it out in production mode
 * because it will have performance impact when throw error
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
